## Server
#server.port=8080
#
## MySQL (XAMPP - root, no password)
#spring.datasource.url=jdbc:mysql://localhost:3306/train_reservation?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
## JWT
#jwt.secret=TrainReservationSecretKeyForJWTAuth2024SuperSecure256BitKey!!
#jwt.expiration=86400000
#
## Jackson
#spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.time-zone=Asia/Kolkata


# Server
server.port=8080

# MySQL (XAMPP - root, no password)
spring.datasource.url=jdbc:mysql://localhost:3306/train_reservation?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ADD THESE FOR FULL QUERY LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT
jwt.secret=TrainReservationSecretKeyForJWTAuth2024SuperSecure256BitKey!!
jwt.expiration=86400000

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata